export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_USER_INFO: "SET_USER_INFO",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYINGLIST_ID: "SET_PLAYINGLIST_ID",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  SET_VOLUME: "SET_VOLUME",
  SET_PLAYING_INDEX: "SET_PLAYING_INDEX",
};
